import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'OneNexium Managed App',
  description: 'AI Generated by OneNexium',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen bg-[#080C14] text-[#F0F4FF]">
        {children}
      </body>
    </html>
  )
}
